site_name: Dwelling Place
site_description: Tracks housing data.
site_author: Dwelling Place
repo_url: https://github.com/dwelling-place/dwelling-place

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
